version: 0.1.0-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\big-voronoi

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -Su mingw-w64-x86_64-ninja mingw-w64-x86_64-speex mingw-w64-x86_64-dumb mingw-w64-x86_64-sfml libcurl-devel"

build: off
build_script:
  - git submodule update --init --recursive
  - make
  - rm -rf out/build
  - cp out\big-voronoi.exe big-voronoi-v0.1.0.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note big-voronoi-v0.1.0.exe

test: off

artifacts:
  - path: big-voronoi-v0.1.0.exe

deploy:
  provider: GitHub
  artifact: big-voronoi-v0.1.0.exe
  auth_token:
    secure: BWR7k6DbZ/cdsDfg530lFNhcBKP8xUBMN2nsZINTS5+J9sEWNHd7pXVFHP7fmswB
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to: nabijaczleweli@gmail.com
    on_build_status_changed: true
